# Generated by Django 5.2 on 2025-04-30 18:53

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, 800], upload_to='about/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
