# Generated by Django 5.2 on 2025-08-23 10:51

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': '3) Мы шьем',
                'verbose_name_plural': '3) Мы шьем',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='partners/', verbose_name='Фотография')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': '4) Партнеры',
                'verbose_name_plural': '4) Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('descriptions', models.TextField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '2) Услуга',
                'verbose_name_plural': '2) Услуги',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('slogan', models.CharField(max_length=100, verbose_name='Слоган')),
                ('slogan_description', models.TextField(verbose_name='Описание слогана')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип')),
                ('icon', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Иконка')),
                ('locate', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': '1) Настройки',
                'verbose_name_plural': '1) Настройки',
            },
        ),
    ]
