# Generated by Django 5.2 on 2025-05-04 00:31

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=100, verbose_name='Услуга')),
                ('descriptions', models.TextField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '2) Услуга',
                'verbose_name_plural': '2) Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Настройки', 'verbose_name_plural': '1) Настройки'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='sliders/', verbose_name='Фото'),
        ),
    ]
