# Generated by Django 5.2 on 2025-06-25 02:25

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_service_alter_settings_options_alter_settings_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='partners/', verbose_name='Фотография')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': '3) Партнеры',
                'verbose_name_plural': '3) Партнеры',
            },
        ),
    ]
