# Generated by Django 5.2 on 2025-08-14 05:40

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='slogan',
            field=models.CharField(default=1, max_length=100, verbose_name='Слоган'),
            preserve_default=False,
        ),
    ]
