# Generated by Django 5.2 on 2025-08-14 15:38

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_settings_icon_settings_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Иконка'),
        ),
    ]
