# Generated by Django 5.2 on 2025-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_settings_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='slogan_description',
            field=models.TextField(default=1, verbose_name='Описание слогана'),
            preserve_default=False,
        ),
    ]
