# Generated by Django 5.2 on 2025-08-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_service_category_alter_service_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
