# Generated by Django 5.2 on 2025-08-15 17:43

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_delete_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='service/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': '3) Мы шьем',
                'verbose_name_plural': '3) Мы шьем',
            },
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': '4) Партнеры', 'verbose_name_plural': '4) Партнеры'},
        ),
    ]
