# Generated by Django 5.2 on 2025-08-23 10:51

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('experience', models.IntegerField(verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': '2) О нас',
                'verbose_name_plural': '2) О нас',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='numbers/', verbose_name='Фотография заднего фона')),
                ('icon', models.CharField(choices=[('fa-tshirt', 'Футболка'), ('fa-hat-cowboy', 'Шляпа'), ('fa-socks', 'Носки'), ('fa-vest', 'Жилет'), ('fa-vest-patches', 'Жилет с заплатками'), ('fa-scissors', 'Ножницы'), ('fa-ruler', 'Линейка'), ('fa-ruler-combined', 'Сантиметр'), ('fa-tape', 'Сантиметровая лента'), ('fa-pen-ruler', 'Лекало'), ('fa-print', 'Принтер для выкроек'), ('fa-box-open', 'Коробка с тканью'), ('fa-boxes', 'Упаковки'), ('fa-cut', 'Раскрой'), ('fa-vector-square', 'Выкройка'), ('fa-th', 'Лекала'), ('fa-users', 'Команда'), ('fa-star', 'Качество'), ('fa-certificate', 'Сертификат'), ('fa-award', 'Награда'), ('fa-medal', 'Медаль'), ('fa-thumbs-up', 'Качество'), ('fa-hands-helping', 'Помощь')], max_length=100, verbose_name='Иконка')),
                ('number', models.IntegerField(verbose_name='в числах')),
                ('descriptions', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '3) Мы в числах',
                'verbose_name_plural': '3) Мы в числах',
            },
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Услуги')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('icon', models.CharField(max_length=100, verbose_name='Иконка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_service', to='index.about')),
            ],
            options={
                'verbose_name': 'Почему мы лучше',
                'verbose_name_plural': 'Почему мы лучше',
            },
        ),
    ]
