# Generated by Django 5.2 on 2025-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
    ]
