# Generated by Django 5.2 on 2025-05-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_about_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '2) О нас', 'verbose_name_plural': '2) О нас'},
        ),
    ]
