# Generated by Django 5.2 on 2025-05-04 00:53

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='numbers/', verbose_name='Фотография заднего фона')),
                ('icon', models.CharField(choices=[('flaticon-suit', 'Костюм'), ('flaticon-sewing-machine', 'Швейная машина'), ('flaticon-tailor', 'Портной'), ('flaticon-scissors', 'Ножницы'), ('flaticon-ruler', 'Линейка'), ('flaticon-yarn', 'Пряжа'), ('flaticon-dress', 'Платье'), ('flaticon-hanger', 'Вешалка'), ('flaticon-needle', 'Игла'), ('flaticon-button', 'Пуговица')], max_length=100, verbose_name='Иконка')),
                ('number', models.IntegerField(verbose_name='в числах')),
                ('descriptions', models.TextField(max_length=30, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '3) Мы в числах',
                'verbose_name_plural': '3) Мы в числах',
            },
        ),
    ]
