# Generated by Django 5.2 on 2025-06-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='icon',
            field=models.CharField(choices=[('fa-tshirt', 'Футболка'), ('fa-hat-cowboy', 'Шляпа'), ('fa-socks', 'Носки'), ('fa-vest', 'Жилет'), ('fa-vest-patches', 'Жилет с заплатками'), ('fa-scissors', 'Ножницы'), ('fa-ruler', 'Линейка'), ('fa-ruler-combined', 'Сантиметр'), ('fa-tape', 'Сантиметровая лента'), ('fa-pen-ruler', 'Лекало'), ('fa-print', 'Принтер для выкроек'), ('fa-box-open', 'Коробка с тканью'), ('fa-boxes', 'Упаковки'), ('fa-cut', 'Раскрой'), ('fa-vector-square', 'Выкройка'), ('fa-th', 'Лекала'), ('fa-users', 'Команда'), ('fa-star', 'Качество'), ('fa-certificate', 'Сертификат'), ('fa-award', 'Награда'), ('fa-medal', 'Медаль'), ('fa-thumbs-up', 'Качество'), ('fa-hands-helping', 'Помощь')], max_length=100, verbose_name='Иконка'),
        ),
    ]
