# Generated by Django 5.2 on 2025-06-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_numbers_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='descriptions',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
    ]
