# Generated by Django 5.2 on 2025-06-24 23:58

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_numbers_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='reviews_image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': '4) Фотографии Отзывы',
                'verbose_name_plural': '4) Фотографии Отзывы',
            },
        ),
    ]
