# Generated by Django 5.2 on 2025-06-25 01:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_reviews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews_image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=85, scale=None, size=[300, 300], upload_to='reviews_image/', verbose_name='Фотография'),
        ),
    ]
