# Generated by Django 5.2 on 2025-08-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_reviews_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_2',
        ),
    ]
