# Generated by Django 5.2 on 2025-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_about_image_1_remove_about_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutservice',
            name='icon',
            field=models.CharField(default=1, max_length=100, verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutservice',
            name='subtitle',
            field=models.CharField(default=1, max_length=100, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
