# Generated by Django 5.2 on 2025-08-15 12:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_aboutservice_icon_aboutservice_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutservice',
            options={'verbose_name': 'Почему мы лучше', 'verbose_name_plural': 'Почему мы лучше'},
        ),
        migrations.AlterField(
            model_name='about',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
