# Generated by Django 5.2 on 2025-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_aboutservice_options_alter_about_descriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews_Image',
        ),
    ]
